# Generated by Django 5.2.7 on 2025-10-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_certo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimaModel',
        ),
    ]
